version = 0.1
[default.deploy.parameters]
stack_name = "wine-emporium-sam"
resolve_s3 = true
s3_prefix = "wine-emporium"
region = "sa-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = true