version = 0.1
[default.deploy.parameters]
stack_name = "wine-emporium-api"
resolve_s3 = true
s3_prefix = "wine-emporium-api"
region = "sa-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = false 
image_repositories = []
