AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: wine-emporium-api

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  WineFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: WineFunction
      Handler: wine.Handler::handleRequest
      Runtime: java17
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        HttpRequest:
          Type: Api
          Properties:
            Path: /wine/{proxy+}
            Method: ANY

Outputs:
  ApiGatewayRestApi:
    Description: "API Gateway endpoint wine emporium"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"