AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: wine-emporium-api

Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: production
      Cors:
        AllowOrigin: "'*'"
        AllowHeaders: "'*'"
        AllowCredentials: "'true'"
      EndpointConfiguration: REGIONAL
      Domain:
        DomainName: wine-emporium-api.toools.space
        CertificateArn: arn:aws:acm:sa-east-1:447988592397:certificate/936b6c01-bace-47e0-b976-493bd238fa09
        Route53:
          HostedZoneName: "toools.space."

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "wine-emporium-tb"
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  wineHandler:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: !Sub '${AWS::StackName}-wine-handler'
      CodeUri: WineFunction
      Handler: wine.Handler::handleRequest
      Runtime: java17
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: "*"
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        Api:
          Type: Api
          Properties:
            Path: /wine
            Method: ANY
            RestApiId: !Ref ApiGatewayApi