name: infra

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

env:
  AWS_REGION: sa-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: install serverless
        run: npm install -g serverless

      - name: resolve dependencies
        run: npm ci

      - name: request certificate
        run: |
            sls create-cert --verbose
        
      - name: request domain
        run: |
          sls create_domain --verbose

      - name: deploy
        run: |
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            
            sls deploy --verbose
